### ISSUE TITLE
RSS feed fails to update on fetch error in any URL

### ISSUE THREAD

**Issue by sansmoraxz** [OlegWock/anori#140]
Feed fails to update if processing any of the provided urls results in error.

**Expected behaviour:** Ignore the url which resulted in error.

Not sure if this would help but here are the console logs (one of my RSS feed was returning html page rather than RSS feed):
```log
background.js:1 Error getting RSS feed TypeError: Failed to fetch
    at Na (background.js:1:238623)
    at Object.getFeedText (background.js:1:243833)
    at background.js:1:262064
    at 399.js:53:14711
2start.js:1 Error while parsing rss feeds Error: Attribute without value
Line: 10
Column: 39
Char: s
    at A (3.js:10:6349)
    at x (3.js:10:6725)
    at i.write (3.js:9:24896)
    at i.parseString (3.js:12:25461)
    at i.parseString (3.js:12:19882)
    at 3.js:9:6385
    at new Promise (<anonymous>)
    at t.exports.parseString (3.js:9:6349)
    at start.js:1:110085
    at Array.map (<anonymous>)
```

**Comment by sansmoraxz** [comment]
Possible culprits:-

https://github.com/OlegWock/anori/blob/d5bdb1aaaf0f61e727baa4741a73904cee0ed8b4/src/plugins/rss/utils.ts#L63-L74

What's happening is I think if some of the promises are rejected, the entire function is rejected, resulting in the formentioned error.

It's generally [not recommended to use `Promise.all` if you need fetch the values.](https://chrysanthos.xyz/article/dont-ever-use-promise-all/)

**Comment by OlegWock** [comment]
Hello! This should be fixed in version 1.16.2. I'll upload it to stores today, but it will take a few more days to get it published. Please let me know if issue still persist after the update
